### PR TITLE
use utf-8 encoding for resources character regex string

### PR DESCRIPTION
**Pull request by rcarlsen**
this was breaking when attempting to build the WeatherWatch app by Katharine:
https://github.com/Katharine/WeatherWatch

### CODE REVIEW

**Comment by martijnthe** [comment]
@rcarlsen did this happen when building with a local toolchain? or cloudpebble?

**Comment by rcarlsen** [comment]
Local toolchain; did not try cloudpebble.

**Comment by Katharine** [comment]
CloudPebble already has a fix similar to this. Since I used CloudPebble to build the thing, I forgot it wouldn't work on the standard SDK.

**Comment by asquelt** [comment]
this doesn't seem to work with all unicode, ie.

```
u'characterRegex': u'[0-9a-z\u0119\xf3\u0105\u015b\u0142\u017c\u017a\u0144,. ]'
```

doesn't rasterize approperiate nationals

```
ęóąśłżźćń
```

**Comment by rcarlsen** [comment]
Much has changed since this request was issued. Seems like a dead end. Perhaps SDK v2.0 has addressed it (sounds like Cloud Pebble already has).

**Comment by sarfata** [comment]
We fixed this in the SDK.

**Comment by martijnthe** [comment]
Hey Robert! I've tried reaching you via (unused?) FB and (old?) email.
Want to shoot me a message at martijn [at] getpebble.com ?
Thanks :)

**Pull request closed without merging**
