### PR TITLE
adding missing requirements.txt file

### PR DESCRIPTION
**Pull request by rcarlsen**

### CODE REVIEW

**Comment by evanstoddard** [comment]
make a file called requirements.txt under Pebble/sdk and put this in the file:  

Pillow==2.0.0
freetype-py==1.0
sh==1.08

**Comment by rcarlsen** [comment]
Yes, that's what the commit attached to this PR does.

**Comment by evanstoddard** [comment]
Sorry I'm new to svn and git

**Comment by rcarlsen** [comment]
Welcome! 

Above your comment there is a panel describing a commit included with this pull request. Click the blue short commit ID (often called a hash or SHA) at the right side to review the code suggested for inclusion in this repo. 

-r

**Comment by follower** [comment]
Thanks for the report.

As of PebbleKit v1.1.1 this issue has been fixed: https://github.com/pebble/pebblekit/blob/master/Pebble/sdk/requirements.txt

**Comment by rcarlsen** [comment]
Thanks for the update.

**Pull request closed without merging**
